curl 'https://app.inspekthor.com/minor/20' &
curl 'https://app.inspekthor.com/minor/20' &
curl 'https://app.inspekthor.com/minor/20' &
curl 'https://app.inspekthor.com/minor/20' &
curl 'https://app.inspekthor.com/minor/20' &
curl 'https://app.inspekthor.com/minor/20' &
curl 'https://app.inspekthor.com/minor/20' &
curl 'https://app.inspekthor.com/minor/20' &
curl 'https://app.inspekthor.com/minor/20' &
curl 'https://app.inspekthor.com/minor/20' &