curl 'https://app.inspekthor.com/minor/5' &
curl 'https://app.inspekthor.com/minor/5' &
curl 'https://app.inspekthor.com/minor/5' &
curl 'https://app.inspekthor.com/minor/5' &
curl 'https://app.inspekthor.com/minor/5' &
curl 'https://app.inspekthor.com/minor/5' &
curl 'https://app.inspekthor.com/minor/5' &
curl 'https://app.inspekthor.com/minor/5' &
curl 'https://app.inspekthor.com/minor/5' &
curl 'https://app.inspekthor.com/minor/5' &